// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8NYaCWKcHIHaut2DkaaTtoFtiL1Ssnss',
    appId: '1:368396061530:web:8b3405438cf5432ec78163',
    messagingSenderId: '368396061530',
    projectId: 'secondbrand-db',
    authDomain: 'secondbrand-db.firebaseapp.com',
    storageBucket: 'secondbrand-db.appspot.com',
    measurementId: 'G-D6JCP27WW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS89Adryy8fymGKOy69WGHNmgQQCUyLIM',
    appId: '1:368396061530:android:4d1ab7c35678304ec78163',
    messagingSenderId: '368396061530',
    projectId: 'secondbrand-db',
    storageBucket: 'secondbrand-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuERfP7X4EwOlNQcbp9mh8NImitid2Tt8',
    appId: '1:368396061530:ios:5badae8600784d1cc78163',
    messagingSenderId: '368396061530',
    projectId: 'secondbrand-db',
    storageBucket: 'secondbrand-db.appspot.com',
    iosBundleId: 'com.example.secondbrand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuERfP7X4EwOlNQcbp9mh8NImitid2Tt8',
    appId: '1:368396061530:ios:5badae8600784d1cc78163',
    messagingSenderId: '368396061530',
    projectId: 'secondbrand-db',
    storageBucket: 'secondbrand-db.appspot.com',
    iosBundleId: 'com.example.secondbrand',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8NYaCWKcHIHaut2DkaaTtoFtiL1Ssnss',
    appId: '1:368396061530:web:1c61cee8ebf45ec4c78163',
    messagingSenderId: '368396061530',
    projectId: 'secondbrand-db',
    authDomain: 'secondbrand-db.firebaseapp.com',
    storageBucket: 'secondbrand-db.appspot.com',
    measurementId: 'G-LN1RC45BP8',
  );
}
